routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


// Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
  //============================================================================
  Route::get('/blog', 'BlogController@index')->name('blog');
  Route::get('/blog/create','BlogController@createBlog')->name('create_blog');
  Route::post('/save','BlogController@saveBlog');
  Route::get('/blog/index','BlogController@showAllBlogs')->name('show_blog');
  Route::get('/hapus/{id_post}','BlogController@hapus')->name('delete_blog');
  Route::get('/edit/{id_post}','BlogController@edit')->name('edit_blog');
  Route::post('/update','BlogController@update');
  Route::get('/view/{id_post}','BlogController@view')->name('view_blog');
  // ===========================================================================
  Route::resource('chatpage', 'MessageController', ['except' => ['show']]);
	Route::get('/chatpage', 'MessageController@index')->name('chatpage');
	Route::get('/message/{id}', 'MessageController@getMessage')->name('message');
	Route::post('message', 'MessageController@sendMessage');
  // ===========================================================================
	Route::get('/home', 'HomeController@index')->name('home');
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
	Route::get('{page}', ['as' => 'page.index', 'uses' => 'PageController@index']);

});

resources/views/layouts/navbars/sidebar.blade.php
<div class="sidebar" data-color="blue">
  <!--
    Tip 1: You can change the color of the sidebar using: data-color="blue | green | orange | red | yellow"
-->
  <div class="logo">
    <a class="simple-text logo-mini" href="/blog">
      {{ __('T') }}
    </a>
    <a class="simple-text logo-normal" href="/blog">
      {{ __('Travelink') }}
    </a>

  </div>
  <div class="sidebar-wrapper" id="sidebar-wrapper">
    <ul class="nav">
      <li class="@if ($activePage == 'blogpage') active @endif">
        <a href="{{ route('blog') }}">
          <i class="now-ui-icons design_app"></i>
          <p>{{ __('BLOG') }}</p>
        </a>
      </li>

      <li class="@if ($activePage == 'chatpage') active @endif">
        <a href="{{ route('chatpage') }}">
          <i class="now-ui-icons design_app"></i>
          <p>{{ __('CHATROOM') }}</p>
        </a>
      </li>



      <!-- <li>
        <a data-toggle="collapse" href="#laravelExamples">
            <i class="fab fa-laravel"></i>
          <p>
            {{ __("Laravel Examples") }}
            <b class="caret"></b>
          </p>
        </a>
        <div class="collapse show" id="laravelExamples">
          <ul class="nav">
            <li class="@if ($activePage == 'profile') active @endif">
              <a href="{{ route('profile.edit') }}">
                <i class="now-ui-icons users_single-02"></i>
                <p> {{ __("User Profile") }} </p>
              </a>
            </li>
            <li class="@if ($activePage == 'users') active @endif">
              <a href="{{ route('user.index') }}">
                <i class="now-ui-icons design_bullet-list-67"></i>
                <p> {{ __("User Management") }} </p>
              </a>
            </li>
          </ul>
        </div>
      <li class="@if ($activePage == 'icons') active @endif">
        <a href="{{ route('page.index','icons') }}">
          <i class="now-ui-icons education_atom"></i>
          <p>{{ __('Icons') }}</p>
        </a>
      </li>
      <li class = "@if ($activePage == 'maps') active @endif">
        <a href="{{ route('page.index','maps') }}">
          <i class="now-ui-icons location_map-big"></i>
          <p>{{ __('Maps') }}</p>
        </a>
      </li>
      <li class = " @if ($activePage == 'notifications') active @endif">
        <a href="{{ route('page.index','notifications') }}">
          <i class="now-ui-icons ui-1_bell-53"></i>
          <p>{{ __('Notifications') }}</p>
        </a>
      </li>
      <li class = " @if ($activePage == 'table') active @endif">
        <a href="{{ route('page.index','table') }}">
          <i class="now-ui-icons design_bullet-list-67"></i>
          <p>{{ __('Table List') }}</p>
        </a>
      </li>
      <li class = "@if ($activePage == 'typography') active @endif">
        <a href="{{ route('page.index','typography') }}">
          <i class="now-ui-icons text_caps-small"></i>
          <p>{{ __('Typography') }}</p>
        </a>
      </li> -->
      <!-- <li class = "@if ($activePage == 'upgrade') active @endif active-pro">
        <a href="{{ route('page.index','upgrade') }}">
          <i class="now-ui-icons arrows-1_cloud-download-93"></i>
          <p>{{ __('Upgrade to PRO') }}</p>
        </a>
      </li> -->
    </ul>
  </div>
</div>